[system]
sysDescr[0]=MS-DOS 6.2 / WFWG 3.11
sysObjectID[0]=enterprises.1
sysUpTime[0]=48993
sysContact[0]=Paulo, Ricardo & Rui
sysName[0]=This Host
sysLocation[0]=FCUL
sysServices[0]=127

[interfaces]
ifNumber[0]=2
ifIndex[1]=1
ifDescr[1]=Ethernet
ifMtu[1]=1500
ifSpeed[1]=100000000
ifPhysAddress[1]=01:02:03:04:05:06
ifAdminStatus[1]=0
ifInUcastPkts[1]=12345
ifOutUcastPkts[1]=12345
ifInOctets[1]=12345678
ifOutOctets[1]=23456789
ifIndex[2]=2
ifDescr[2]=Ethernet
ifMtu[2]=1500
ifSpeed[2]=100000000
ifPhysAddress[2]=02:03:04:05:06:07
ifAdminStatus[2]=1
ifInUcastPkts[2]=23456
ifOutUcastPkts[2]=23456
ifInOctets[2]=23456789
ifOutOctets[2]=12345678

[at]
atIfIndex[1]=1
atIfIndex[2]=2
atPhysAddress[1]=01:02:03:04:05:06
atPhysAddress[2]=02:03:04:05:06:07
atNetAddress[1]=192.67.76.69
atNetAddress[2]=192.168.40.22

[ip]
ipAdEntAddr[1]=192.67.76.69
ipAdEntAddr[2]=193.136.156.69
ipAdEntAddr[3]=192.67.77.69
ipAdEntAddr[4]=192.67.78.69
ipAdEntAddr[5]=192.168.40.22
ipAdEntIfIndex[1]=1
ipAdEntIfIndex[2]=3
ipAdEntIfIndex[3]=4
ipAdEntIfIndex[4]=5
ipAdEntIfIndex[5]=2

